## CIVE4200  Assignment 2, Question 4 - Compact Solution

This notebook illustrates the use of the Python version of CAL86 (CAL90?) to solve Question 4 of Assignment 2 of CIVE4200, 2015/16.  In this example, all CAL commands are in one cell.

![Element](.img/A2Q2-fig0.svg)

Neglecting axial deformations (ie, assuming infinite axial stiffness), the element
degree-of-freedom numbering is as follows: ![Element](img/A2Q2-fig1.svg)
Note that the numbering starts at 0 (zero) **not** 1 (one).  This is to keep array indexing
consistent with the underlying Python array library.

![Element](img/A2Q2-fig2.svg)

In [1]:
import PyCAL86
import numpy as np

In [2]:
%%CAL86 -v
C        NAME: JOSHUA WOODS
C        COURSE CIVE 4200
C
C QUESTION 2 FROM ASSIGNMENT 2 SOLVED USING CAL90 USING BASIC COMMANDS AND ADDK IGNORING AXIAL DEFORMATIONS
C
C PROBLEM
C
C STIFFNESS CALCULATION
C
C MEMBER 1 (HORIZONTAL ON LEFT , L=4 EI=70.2E3)
C
LOAD K1 R=4 C=4
13.16E3 26.33E3 -13.16E3 26.33E3
26.33E3 70.2E3 -26.67E3 35.1E3
-13.16E3 -26.67E3 13.16E3 -26.33E3
26.33E3 35.1E3 -26.33E3 70.2E3
PRINT K1

C
C MEMBER2 (HORIZONTAL ON RIGHT, L=2, EI=70.2E3)
C
LOAD K2 R=4 C=4
105.3E3 105.3E3 -105.3E3 105.3E3
105.3E3 140.4E3 -105.3E3 70.2E3
-105.3E3 -105.3E3 105.3E3 -105.3E3
105.3E3 70.2E3 -105.3E3 140.4E3
PRINT K2

C
C MEMBER 3 (VERTICAL COLUMN MEMBER, L=5, EI=111.2E3, THETA=90)
LOAD KK3 R=4 C=4
10.675E3 26.69E3 -10.675E3 26.69E3
26.69E3 88.96E3 -26.69E3 44.48E3
-10.675E3 -26.69E3 10.675E3 -26.69E3
26.69E3 44.48E3 -26.69E3 88.96E3
PRINT KK3

C
C TRANSFORMATION MATRIX FOR THETA=90
C
LOAD A1 R=4 C=4
1. 0. 0. 0.
0. 1. 0. 0.
0. 0. 1. 0.
0. 0. 0. 1.
PRINT A1

C
C FORCE-DISPLACEMENT TRANFORMATION MATRIX
C
MULT KK3 A1 KA3
PRINT KA3

C
TRAN A1 A1T
MULT A1T KA3 K3
PRINT K3

C
C DIRECT STIFFNESS ASSEMBLY OF GLOBAL STRUCTURAL STIFFNESS
C
C LOCAL-STRUCTURAL DOF RELATION OR LOCATION ARRAY
C
LOADI LM R=4 C=3
4 5 7
0 1 8
5 3 6
1 2 1
PRINT LM

C
ZERO K R=9 C=9
ADDK K K1 LM N=0
ADDK K K2 LM N=1
ADDK K K3 LM N=2
C
C ASSEMBLED GLOBAL STRUCTURAL STIFFNESS
PRINT K

C
C LOAD VECTOR WITH FIXED END FORCES
LOAD R R=9 C=1
-16.
12.
4.
-17.
0
0
0
0
0
PRINT R
C
C DISPLACEMENT VECTOR
ZERO D R=9 C=1

C  IN THE FOLLOWING, PS IS PARTITION SIZE (# OF UNCONSTRAINED DOFs)
PSOLVE K D R PS=4
PRINT D
PRINT R
C
C MEMBER FORCES W / FIXED END FORCES
C
MEMFRC K1 D LM F1 N=0
C MEMBER FORCES MEMBER 1
PRINT F1
C
MEMFRC K2 D LM F2 N=1
C MEMBER FORCES MEMBER 2
PRINT F2
C
MEMFRC KA3 D LM F3 N=2
C MEMBER FORCES MEMBER 3
PRINT F3

C
C ADD FIXED END FORCES TO MEMBER 2
C
LOAD FE1 R=4 C=1
24.
16.
24.
-16.
PRINT FE1
C
LOAD FE2 R=4 C=1
12.
4.
12.
-4.
PRINT FE2
C
ADD F1 FE1
ADD F2 FE2
PRINT F1
PRINT F2
C
C PROBLEM COMPLETE ALL MEMBER FORCES AND NODAL DISPLACEMENTS HAVE BEEN DETERMINED
C RETURN

C        NAME: JOSHUA WOODS
C        COURSE CIVE 4200
C
C QUESTION 2 FROM ASSIGNMENT 2 SOLVED USING CAL90 USING BASIC COMMANDS AND ADDK IGNORING AXIAL DEFORMATIONS
C
C PROBLEM
C
C STIFFNESS CALCULATION
C
C MEMBER 1 (HORIZONTAL ON LEFT , L=4 EI=70.2E3)
C
LOAD K1 R=4 C=4
13.16E3 26.33E3 -13.16E3 26.33E3
26.33E3 70.2E3 -26.67E3 35.1E3
-13.16E3 -26.67E3 13.16E3 -26.33E3
26.33E3 35.1E3 -26.33E3 70.2E3
ARRAY NAME = K1    NUMBER OF ROWS =    4 NUMBER OF COLUMNS =    4
PRINT K1
K1:
[[ 13160.  26330. -13160.  26330.]
 [ 26330.  70200. -26670.  35100.]
 [-13160. -26670.  13160. -26330.]
 [ 26330.  35100. -26330.  70200.]]

C
C MEMBER2 (HORIZONTAL ON RIGHT, L=2, EI=70.2E3)
C
LOAD K2 R=4 C=4
105.3E3 105.3E3 -105.3E3 105.3E3
105.3E3 140.4E3 -105.3E3 70.2E3
-105.3E3 -105.3E3 105.3E3 -105.3E3
105.3E3 70.2E3 -105.3E3 140.4E3
ARRAY NAME = K2    NUMBER OF ROWS =    4 NUMBER OF COLUMNS =    4
PRINT K2
K2:
[[ 105300.  105300. -105300.  105300.]
 [ 105300.  140400. -105300.   70200.]
 [-105300. -105300.  1